version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    networks:
      - 4-growth-docker-network

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - 4-growth-docker-network


networks:
  4-growth-docker-network:
    driver: bridge