packages:
  - 'api/**'
  - 'client/**'
  - 'shared/**'
  - 'e2e/**'

catalog:
  # Core
  zod: 3.23.8
  "@types/node": 20.14.2
  typescript: 5.4.5
  typeorm: 0.3.20
  bcrypt: 6.0.0
  "@types/bcrypt": 6.0.0
  # Linting & formatting
  eslint: 8.57.1
  eslint-config-prettier: 9.1.0
  eslint-plugin-prettier: 5.1.3
  prettier: 3.2.5
  "@typescript-eslint/eslint-plugin": 7.9.0
  "@typescript-eslint/parser": 7.9.0
  # Testing
  "@types/jest": 29.5.12
  # Tooling
  ts-node: 10.9.2
  # Shared libraries
  "@types/lodash": 4.17.4
  lodash: 4.17.21
  qs: 6.13.0
  "@types/qs": 6.9.16
  class-transformer: 0.5.1
  class-validator: 0.14.1

overrides:
  d3-color: 3.1.0
