packages:
  - "api/**"
  - "client/**"
  - "shared/**"
  - "e2e/**"

catalog:
  # Core
  zod: 3.25.76
  "@types/node": 25.3.0
  typescript: 5.9.3
  typeorm: 0.3.28
  bcrypt: 6.0.0
  "@types/bcrypt": 6.0.0
  # Linting & formatting
  eslint: 10.0.2
  eslint-config-prettier: 10.1.8
  eslint-plugin-prettier: 5.5.5
  prettier: 3.8.1
  "@typescript-eslint/eslint-plugin": 8.56.1
  "@typescript-eslint/parser": 8.56.1
  # Testing
  "@types/jest": 30.0.0
  # Tooling
  ts-node: 10.9.2
  # Shared libraries
  "@types/lodash": 4.17.24
  lodash: 4.17.23
  qs: 6.15.0
  "@types/qs": 6.14.0
  class-transformer: 0.5.1
  class-validator: 0.14.4

# Note: overrides are in root package.json (pnpm.overrides) — pnpm 9.x does not read them from here
