packages:
  - "api/**"
  - "client/**"
  - "shared/**"
  - "e2e/**"

catalog:
  # Core
  zod: 3.25.76
  "@types/node": 20.19.33
  typescript: 5.4.5
  typeorm: 0.3.28
  bcrypt: 6.0.0
  "@types/bcrypt": 6.0.0
  # Linting & formatting
  eslint: 8.57.1
  eslint-config-prettier: 9.1.2
  eslint-plugin-prettier: 5.1.3
  prettier: 3.2.5
  "@typescript-eslint/eslint-plugin": 7.18.0
  "@typescript-eslint/parser": 7.18.0
  # Testing
  "@types/jest": 29.5.14
  # Tooling
  ts-node: 10.9.2
  # Shared libraries
  "@types/lodash": 4.17.4
  lodash: 4.17.23
  qs: 6.14.2
  "@types/qs": 6.9.18
  class-transformer: 0.5.1
  class-validator: 0.14.4

# Note: overrides are in root package.json (pnpm.overrides) — pnpm 9.x does not read them from here
