insert
into
    survey_responses (
    org_4growth,
    sector_4growth,
    "type",
    "location",
    prim_agri,
    prim_agri_other,
    prim_forest,
    prim_forest_other,
    org_farm,
    org_size,
    reg_cons,
    considerations,
    gm01,
    gm02,
    gm02_other,
    gm04,
    gm04_other,
    gm04_1,
    integrated_digi_tech,
    digitech_agri,
    digitech_agri_other,
    digitaltech_forestry,
    digitaltech_forestry_other,
    goals_to_adopt,
    specify_challenges_tech_adopt,
    lvl_digitalisation,
    prim_function_tech,
    adopt_level_tech,
    challenges_tech_adopt,
    specify_challenges,
    further_integration,
    specify_barriers,
    digitech_userneeds,
    adv_tech,
    adv_tech_other,
    limitations_tech,
    specify_limitations,
    network_connect,
    network_connectivity,
    reliability_network,
    barriers_connectivity,
    devices_network,
    acp6_1,
    acp6_1_other,
    acp6_2,
    acp6_3,
    acp6_4,
    acp6_4_1,
    dmdsp7_1,
    dmdsp7_2,
    dmdsp7_3,
    dmdsp7_4,
    dmdsp7_5,
    dmdsp7_6,
    dmdsp7_7,
    dmdsp7_8,
    dmdsp7_9,
    dmdsp7_10,
    dsdf8_1,
    dsdf8_2,
    dsdf8_1_1,
    dsdf8_1_2,
    dsdf8_3,
    dsdf8_4,
    dsdf8_4_1,
    dsdf8_5,
    dsdf8_6,
    dsdf8_7,
    dsdf8_8,
    dsdf8_9,
    dsdf8_9_1,
    dsdf8_10,
    digitech_social_benefits,
    digitech_job_creation,
    digitech_overall_social,
    digitech_efficiency,
    digitech_input,
    digitech_overall_economic,
    digitech_sustainability,
    digitech_impacts_footprint,
    didgitech_energy_efficiency,
    digitech_biodiversity,
    digitech_track_sustainability,
    plan_upgrade_digitech,
    facilitate_expansion_upgrade,
    type_of_developments,
    ac12_1
)
values (
           'test org 1',
           'Both',
           'Forester',
           'Czechia',
           'Mixed farming (crops and animal)',
           null,
           'Forestry inventory and mapping',
           null,
           'No',
           'Large-scale/National-International',
           'Yes',
           'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
           'Hindered',
           'Other namely',
           'ddfa',
           'Other namely',
           'fdsaf',
           null,
           'No',
           null,
           null,
           null,
           null,
           false,
           null,
           '1',
           'On-farm activities',
           'Preliminary',
           'No',
           null,
           false,
           null,
           'Not at all'
               'Increased efficiency and productivity',
           null,
           'No',
           null,
           false,
           null,
           null,
           false,
           'Initial investment',
           false,
           'Low',
           'No',
           'No',
           null,
           'Yes',
           'Open sharing',
           'Soil data',
           'No',
           'Field Data Collection Apps',
           null,
           'No',
           'No',
           'Impede',
           '<25%',
           'jdhfajahdkv',
           'Yes',
           'jdanbcjkb',
           'vbnajdf',
           'fckalj',
           'Yes',
           'cnjsjkdn',
           'Yes',
           'Yes',
           null,
           null,
           'fjajcn lfkwekfo 8 kfjdsakfj',
           'Farm-level data',
           'No',
           null,
           'On-premises servers/local storage facilities',
           'No',
           'Yes',
           'Neutral',
           'No',
           'Yes',
           'Positive',
           'Yes',
           'No',
           'Yes',
           'Negative',
           'Yes',
           'Yes',
           'Better connectivity/Infrastructure',
           'Advancements in existing technologies',
           null
       );