name: 'Install node modules'
description: 'Installs node modules and handles caching'
inputs:
  working-directory:
    description: 'The working directory where all the package manager files will be read from'
    required: true
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Compute cache key
      id: compute-key
      shell: bash
      run: |
        echo "NODE_MODULES_CACHE_KEY=${{ runner.os }}-node_modules-$(echo ${{ inputs.working-directory }}/pnpm-lock.yaml | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

    - name: Check cache key
      id: check-cache-key
      shell: bash
      run: | 
        echo $GITHUB_ENV

    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: ${{ inputs.working-directory }}/node_modules
        key: ${{ env.NODE_MODULES_CACHE_KEY }}
        restore-keys: |
          ${{ runner.os }}-node_modules-${{ inputs.working-directory }}

    - name: Check cache status
      shell: bash
      run: |
        echo "Cache hit: ${{ steps.cache-node-modules.outputs.cache-hit }}"

    - name: Install pnpm dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: pnpm install

    # - name: Cache node_modules after installation
    #   if: steps.cache-node-modules.outputs.cache-hit != 'true'
    #   uses: actions/cache@v3
    #   with:
    #     path: ${{ inputs.working-directory }}/node_modules
    #     key: ${{ env.NODE_MODULES_CACHE_KEY }}