name: API Tests

on:
  push:
    paths:
      - 'api/**'
      - '.github/workflows/api-tests.yml'
      - '/*'               # include changes in root
      - '!client/**'       # exclude client folder
      - '!infrastructure/**'  # exclude infra folder

  workflow_dispatch:


jobs:

  api-tests-e2e:
    name: API E2E Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: pnpm/action-setup@v4

      - name: Install API dependencies
        working-directory: api
        run: pnpm install

      - name: Run API E2E tests
        working-directory: api
        run: pnpm test:e2e
