name: Client Tests

on:
  push:
    paths:
      - 'api/**'
      - '.github/workflows/client-tests.yml'

  workflow_dispatch:


jobs:
  api-tests-e2e:
    name: Client Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: pnpm/action-setup@v4

      - name: Install Client dependencies
        working-directory: client
        run: pnpm install

      - name: Run Client tests
        working-directory: client
        run: pnpm test
