name: e2e Tests

on:
  push:
    paths:
      - 'e2e/**'
      - 'shared/**'
      - 'api/**'
      - 'client/**'
      - '.github/workflows/e2e-tests.yml'
      - '/*'               # include changes in root
      - '!infrastructure/**'  # exclude infra folder

  workflow_dispatch:


jobs:
  e2e-tests:
    name: e2e tests
    runs-on: ubuntu-22.04

    services:
      database:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: 4growth
          POSTGRES_PASSWORD: 4growth
          POSTGRES_DB: 4growth

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: pnpm/action-setup@v4

      - name: Install e2e dependencies
        working-directory: e2e
        run: pnpm install

      - name: Install Chromium browser
        working-directory: e2e
        run: npx playwright install --with-deps chromium

      - name: Run e2e tests
        working-directory: e2e
        run: pnpm test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
